/**
 * Index file generator
 *
 * Generates _models/index.ts that re-exports all model classes
 * and provides an allModels array.
 */
import type { GeneratedFile } from './types.js';

interface ModelExportEntry {
  /** File name without .ts (e.g. 'requirement') */
  fileName: string;
  /** Class names to export (e.g. ['RequirementModel']) */
  classNames: string[];
}

/**
 * Derive model class names from generated model file content.
 *
 * Looks for `export { ClassName }` or `export { A, B }` at end of file.
 */
function extractExportedClassNames(content: string): string[] {
  const match = content.match(/export\s*\{([^}]+)\}\s*;?\s*$/m);
  if (!match) return [];
  return match[1].split(',').map(s => s.trim()).filter(Boolean);
}

/**
 * Generate _models/index.ts from a list of generated model files.
 */
export function generateModelsIndex(modelFiles: GeneratedFile[]): GeneratedFile {
  const entries: ModelExportEntry[] = [];

  for (const file of modelFiles) {
    const fileName = file.relativePath
      .replace(/^_models\//, '')
      .replace(/\.ts$/, '');
    const classNames = extractExportedClassNames(file.content);
    if (classNames.length > 0) {
      entries.push({ fileName, classNames });
    }
  }

  entries.sort((a, b) => a.fileName.localeCompare(b.fileName));

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * Model index — generated by speckeeper scaffold');
  lines.push(' */');
  lines.push('');

  for (const entry of entries) {
    lines.push(`export { ${entry.classNames.join(', ')} } from './${entry.fileName}.js';`);
  }

  lines.push('');

  const modelInstanceNames = entries.flatMap(e =>
    e.classNames.filter(n => n.endsWith('Model')),
  );

  if (modelInstanceNames.length > 0) {
    lines.push('import { Model } from \'speckeeper\';');
    lines.push('import type { ZodType } from \'zod\';');
    lines.push('');

    for (const entry of entries) {
      const models = entry.classNames.filter(n => n.endsWith('Model'));
      if (models.length > 0) {
        lines.push(`import { ${models.join(', ')} } from './${entry.fileName}.js';`);
      }
    }

    lines.push('');
    lines.push('// eslint-disable-next-line @typescript-eslint/no-explicit-any');
    lines.push('export const allModels: Model<ZodType>[] = [');

    for (const name of modelInstanceNames) {
      lines.push(`  ${name}.instance as Model<ZodType>,`);
    }

    lines.push('];');
  }

  lines.push('');

  return {
    relativePath: '_models/index.ts',
    content: lines.join('\n'),
  };
}
