/**
 * Model file generator
 *
 * Generates _models/*.ts files for speckeeper-managed nodes
 * by looking up the appropriate template.
 */
import type {
  MermaidNode,
  ResolvedEdge,
  GeneratedFile,
} from './types.js';
import { resolveModelTemplate } from './template-registry.js';
import { MODEL_TEMPLATE_FUNCTIONS } from './templates/index.js';

/**
 * Generate _models/*.ts file for a single speckeeper-managed node.
 *
 * @param node - The mermaid node
 * @param incomingEdges - Edges pointing to this node
 * @param outgoingEdges - Edges from this node
 * @returns GeneratedFile or null if no template matches
 */
export function generateModelFile(
  node: MermaidNode,
  _incomingEdges: ResolvedEdge[],
  _outgoingEdges: ResolvedEdge[],
): GeneratedFile {
  const templateInfo = resolveModelTemplate(node.id);
  const templateFn = MODEL_TEMPLATE_FUNCTIONS[templateInfo.templateName];

  if (!templateFn) {
    const baseFn = MODEL_TEMPLATE_FUNCTIONS['base'];
    return {
      relativePath: `_models/${templateInfo.fileName}.ts`,
      content: baseFn({
        modelId: templateInfo.fileName,
        modelName: templateInfo.modelName,
        idPrefix: templateInfo.defaultIdPrefix,
        level: templateInfo.defaultLevel,
        description: node.label ?? node.id,
      }),
    };
  }

  const content = templateFn({
    modelId: templateInfo.fileName,
    modelName: templateInfo.modelName,
    idPrefix: templateInfo.defaultIdPrefix,
    level: templateInfo.defaultLevel,
    description: node.label ?? node.id,
  });

  return {
    relativePath: `_models/${templateInfo.fileName}.ts`,
    content,
  };
}

/**
 * Generate a spec data file that exports a SpecModule via defineSpecs().
 */
export function generateSpecDataFile(
  node: MermaidNode,
): GeneratedFile {
  const templateInfo = resolveModelTemplate(node.id);
  const className = `${templateInfo.modelName}Model`;
  const typeName = templateInfo.modelName;
  const varName = toCamelCase(templateInfo.modelName) + 's';
  const fileName = templateInfo.fileName;

  const content = `/**
 * ${templateInfo.modelName} Specifications
 *
 * Generated by speckeeper scaffold — add your specs below.
 */
import { defineSpecs } from 'speckeeper';
import type { ${typeName} } from './_models/${fileName}';
import { ${className} } from './_models/${fileName}';

const ${varName}: ${typeName}[] = [
  // { id: '${templateInfo.defaultIdPrefix}-001', name: '...', description: '...' },
];

export default defineSpecs(
  [${className}.instance, ${varName}],
);
`;

  return {
    relativePath: `${fileName}.ts`,
    content,
  };
}

function toCamelCase(pascalCase: string): string {
  return pascalCase.charAt(0).toLowerCase() + pascalCase.slice(1);
}

/**
 * Generate design/index.ts that merges all spec data files.
 */
export function generateDesignIndex(
  speckeeperNodes: MermaidNode[],
): GeneratedFile {
  const generated = new Set<string>();
  const specFiles: { varName: string; fileName: string }[] = [];

  for (const node of speckeeperNodes) {
    const templateInfo = resolveModelTemplate(node.id);
    const key = templateInfo.templateName === 'base'
      ? `base:${node.id}`
      : templateInfo.templateName;

    if (generated.has(key)) continue;
    generated.add(key);

    specFiles.push({
      varName: toCamelCase(templateInfo.modelName),
      fileName: templateInfo.fileName,
    });
  }

  const imports = specFiles
    .map(f => `import ${f.varName} from './${f.fileName}';`)
    .join('\n');
  const args = specFiles.map(f => f.varName).join(', ');

  const content = `/**
 * Design entry point — generated by speckeeper scaffold
 */
import { mergeSpecs } from 'speckeeper';
${imports}

export default mergeSpecs(${args});
`;

  return {
    relativePath: 'index.ts',
    content,
  };
}

/**
 * Generate all model files for speckeeper-managed nodes.
 *
 * Multiple nodes may map to the same template (e.g. SR, FR, NFR → requirement).
 * In that case, only one file is generated (de-duplicated by template name).
 * Also generates a corresponding spec data file and design/index.ts.
 */
export function generateAllModelFiles(
  speckeeperNodes: MermaidNode[],
  resolvedEdges: ResolvedEdge[],
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const generated = new Set<string>();

  for (const node of speckeeperNodes) {
    const templateInfo = resolveModelTemplate(node.id);
    const key = templateInfo.templateName === 'base'
      ? `base:${node.id}`
      : templateInfo.templateName;

    if (generated.has(key)) continue;
    generated.add(key);

    const incoming = resolvedEdges.filter(e => e.targetId === node.id);
    const outgoing = resolvedEdges.filter(e => e.sourceId === node.id);
    files.push(generateModelFile(node, incoming, outgoing));
    files.push(generateSpecDataFile(node));
  }

  files.push(generateDesignIndex(speckeeperNodes));

  return files;
}
