/**
 * Model file generator
 *
 * Generates _models/*.ts files for speckeeper-managed nodes
 * by resolving artifact class from mermaid node classes.
 */
import type {
  MermaidNode,
  ResolvedEdge,
  GeneratedFile,
} from './types.js';
import { isCheckEdge } from './edge-vocabulary.js';
import { resolveModelTemplate } from './template-registry.js';
import { MODEL_TEMPLATE_FUNCTIONS } from './templates/index.js';

// ---------------------------------------------------------------------------
// Checker binding resolution
// ---------------------------------------------------------------------------

export interface CheckerBinding {
  edgeType: 'implements' | 'verifiedBy';
  targetNodeId: string;
  targetClass: string;
}

/**
 * Determine checker bindings for a speckeeper node from its outgoing check edges.
 */
export function resolveCheckerBindings(
  _nodeId: string,
  outgoingEdges: ResolvedEdge[],
  nodes: Map<string, MermaidNode>,
  speckeeperClassName: string,
): CheckerBinding[] {
  const isSpk = (id: string): boolean =>
    nodes.get(id)?.classes.includes(speckeeperClassName) ?? false;

  const bindings: CheckerBinding[] = [];
  const seen = new Set<string>();

  for (const edge of outgoingEdges) {
    if (!isCheckEdge(edge.vocabulary)) continue;
    if (isSpk(edge.targetId)) continue;

    if (seen.has(edge.targetId)) continue;
    seen.add(edge.targetId);

    const targetNode = nodes.get(edge.targetId);
    const targetClass = targetNode?.classes.find(c => c !== speckeeperClassName) ?? edge.targetId.toLowerCase();

    const edgeType = edge.normalizedLabel === 'verifiedBy' ? 'verifiedBy' as const : 'implements' as const;

    bindings.push({ edgeType, targetNodeId: edge.targetId, targetClass });
  }

  return bindings;
}

/**
 * Generate _models/*.ts file for a single speckeeper-managed node.
 *
 * Checker bindings from implements/verifiedBy edges are appended as
 * commented configuration that users can activate.
 */
export function generateModelFile(
  node: MermaidNode,
  _incomingEdges: ResolvedEdge[],
  outgoingEdges: ResolvedEdge[],
  allNodes?: Map<string, MermaidNode>,
): GeneratedFile {
  const templateInfo = resolveModelTemplate(node.id, node.classes, node.subgraph);
  const templateFn = MODEL_TEMPLATE_FUNCTIONS[templateInfo.templateName];

  const params = {
    modelId: templateInfo.fileName,
    modelName: templateInfo.modelName,
    idPrefix: templateInfo.defaultIdPrefix,
    level: templateInfo.defaultLevel,
    description: node.label ?? node.id,
  };

  let content: string;
  if (!templateFn) {
    content = MODEL_TEMPLATE_FUNCTIONS['base'](params);
  } else {
    content = templateFn(params);
  }

  const bindings = allNodes
    ? resolveCheckerBindings(node.id, outgoingEdges, allNodes, 'speckeeper')
    : [];

  if (bindings.length > 0) {
    content += generateCheckerBindingComment(bindings);
  }

  return {
    relativePath: `_models/${templateInfo.fileName}.ts`,
    content,
  };
}

const CHECKER_FACTORY_MAP: Record<string, string> = {
  openapi: 'externalOpenAPIChecker',
  sqlschema: 'externalSqlSchemaChecker',
  test: 'testChecker',
};

function generateCheckerBindingComment(bindings: CheckerBinding[]): string {
  const lines = [
    '',
    '// =============================================================================',
    '// Checker Bindings (auto-detected from flowchart edges)',
    '// =============================================================================',
    '//',
    '// Import and assign to externalChecker in the Model class:',
    "// import { " + bindings.map(b => CHECKER_FACTORY_MAP[b.targetClass] ?? 'externalSsotChecker').join(', ') + " } from 'speckeeper/dsl';",
    '//',
  ];

  for (const b of bindings) {
    const factory = CHECKER_FACTORY_MAP[b.targetClass] ?? `/* custom checker for '${b.targetClass}' */`;
    lines.push(`// ${b.edgeType} → ${b.targetNodeId} (class: ${b.targetClass}): ${factory}`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate a spec data file that exports a SpecModule via defineSpecs().
 */
export function generateSpecDataFile(
  node: MermaidNode,
): GeneratedFile {
  const templateInfo = resolveModelTemplate(node.id, node.classes, node.subgraph);
  const className = `${templateInfo.modelName}Model`;
  const typeName = templateInfo.modelName;
  const varName = toCamelCase(templateInfo.modelName) + 's';
  const fileName = templateInfo.fileName;

  const content = `/**
 * ${templateInfo.modelName} Specifications
 *
 * Generated by speckeeper scaffold — add your specs below.
 */
import { defineSpecs } from 'speckeeper';
import type { ${typeName} } from './_models/${fileName}';
import { ${className} } from './_models/${fileName}';

const ${varName}: ${typeName}[] = [
  // { id: '${templateInfo.defaultIdPrefix}-001', name: '...', description: '...' },
];

export default defineSpecs(
  [${className}.instance, ${varName}],
);
`;

  return {
    relativePath: `${fileName}.ts`,
    content,
  };
}

function toCamelCase(pascalCase: string): string {
  return pascalCase.charAt(0).toLowerCase() + pascalCase.slice(1);
}

/**
 * Generate design/index.ts that merges all spec data files.
 */
export function generateDesignIndex(
  speckeeperNodes: MermaidNode[],
): GeneratedFile {
  const generated = new Set<string>();
  const specFiles: { varName: string; fileName: string }[] = [];

  for (const node of speckeeperNodes) {
    const templateInfo = resolveModelTemplate(node.id, node.classes, node.subgraph);
    const hasArtifactClass = node.classes.some(c => c !== 'speckeeper');
    const key = hasArtifactClass ? templateInfo.fileName : `base:${node.id}`;

    if (generated.has(key)) continue;
    generated.add(key);

    specFiles.push({
      varName: toCamelCase(templateInfo.modelName),
      fileName: templateInfo.fileName,
    });
  }

  const imports = specFiles
    .map(f => `import ${f.varName} from './${f.fileName}';`)
    .join('\n');
  const args = specFiles.map(f => f.varName).join(', ');

  const content = `/**
 * Design entry point — generated by speckeeper scaffold
 */
import { mergeSpecs } from 'speckeeper';
${imports}

export default mergeSpecs(${args});
`;

  return {
    relativePath: 'index.ts',
    content,
  };
}

/**
 * Generate all model files for speckeeper-managed nodes.
 *
 * Multiple nodes with the same artifact class are de-duplicated
 * into a single model file (e.g. FR, SR, NFR with class 'requirement').
 */
export function generateAllModelFiles(
  speckeeperNodes: MermaidNode[],
  resolvedEdges: ResolvedEdge[],
  allNodes?: Map<string, MermaidNode>,
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const generated = new Set<string>();

  const templateNodeGroups = new Map<string, MermaidNode[]>();
  for (const node of speckeeperNodes) {
    const templateInfo = resolveModelTemplate(node.id, node.classes, node.subgraph);
    const hasArtifactClass = node.classes.some(c => c !== 'speckeeper');
    const key = hasArtifactClass ? templateInfo.fileName : `base:${node.id}`;
    const group = templateNodeGroups.get(key) ?? [];
    group.push(node);
    templateNodeGroups.set(key, group);
  }

  for (const node of speckeeperNodes) {
    const templateInfo = resolveModelTemplate(node.id, node.classes, node.subgraph);
    const hasArtifactClass = node.classes.some(c => c !== 'speckeeper');
    const key = hasArtifactClass ? templateInfo.fileName : `base:${node.id}`;

    if (generated.has(key)) continue;
    generated.add(key);

    const groupNodes = templateNodeGroups.get(key) ?? [node];
    const groupNodeIds = new Set(groupNodes.map(n => n.id));
    const incoming = resolvedEdges.filter(e => groupNodeIds.has(e.targetId));
    const outgoing = resolvedEdges.filter(e => groupNodeIds.has(e.sourceId));
    files.push(generateModelFile(node, incoming, outgoing, allNodes));
    files.push(generateSpecDataFile(node));
  }

  files.push(generateDesignIndex(speckeeperNodes));

  return files;
}
