import type { CheckerTemplateParams } from '../types.js';

export function generateBaseChecker(params: CheckerTemplateParams): string {
  return `import type { ExternalChecker, CheckResult } from 'speckeeper';
import type { ${params.sourceModelName} } from '../_models/${params.sourceModelFile}.ts';

/**
 * ${params.checkerName}: verifies ${params.sourceModelName} against external ${params.targetType} artifacts.
 *
 * Generated by speckeeper scaffold — implement check logic.
 */
export const ${toCamelCase(params.checkerName)}: ExternalChecker<${params.sourceModelName}> = {
  targetType: '${params.targetType}',

  sourcePath: () => '.',

  check: (spec, _externalData): CheckResult => {
    const errors: CheckResult['errors'] = [];
    const warnings: CheckResult['warnings'] = [];

    // TODO: implement check logic for ${params.targetType}
    warnings.push({
      message: \`${params.checkerName} not implemented for \${spec.id}\`,
      specId: spec.id,
    });

    return {
      success: errors.length === 0,
      errors,
      warnings,
    };
  },
};
`;
}

function toCamelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
