/**
 * New Command
 * 
 * Generate templates for new model instances
 */

import chalk from 'chalk';
import { join } from 'node:path';
import { writeFileSync, existsSync } from 'node:fs';
import { loadConfig } from '../utils/config-loader.js';
import { getAllModels } from '../core/model.js';

// ============================================================================
// Types
// ============================================================================

export interface NewCommandOptions {
  config?: string;
  type?: string;
  id?: string;
  output?: string;
  dryRun?: boolean;
}

// ============================================================================
// New Command
// ============================================================================

export async function newCommand(options: NewCommandOptions): Promise<void> {
  console.log(chalk.blue('speckeeper new'));
  console.log('');
  
  const cwd = process.cwd();
  const config = await loadConfig(options.config);
  
  // List available types if no type specified
  if (!options.type) {
    console.log(chalk.gray('  Available model types:'));
    const models = getAllModels();
    for (const model of models) {
      console.log(chalk.gray(`    - ${model.id} (${model.name})`));
    }
    console.log('');
    console.log(chalk.gray('  Usage: speckeeper new --type <type> [--id <id>]'));
    return;
  }
  
  // Find model
  const models = getAllModels();
  const model = models.find(m => m.id === options.type);
  
  if (!model) {
    console.error(chalk.red(`  Error: Unknown model type '${options.type}'`));
    console.log(chalk.gray('  Run `speckeeper new` to see available types'));
    process.exit(1);
  }
  
  // Generate ID if not provided
  const id = options.id || `${model.idPrefix}-${String(Date.now()).slice(-6)}`;
  
  // Generate template
  const template = generateTemplate(model, id);
  
  if (options.dryRun) {
    console.log(chalk.gray('  Template (dry run):'));
    console.log('');
    console.log(template);
    return;
  }
  
  // Write template to file
  const outputDir = options.output || join(cwd, config.designDir || 'design');
  const outputFile = join(outputDir, `${model.id}-${id}.ts`);
  
  if (existsSync(outputFile)) {
    console.error(chalk.red(`  Error: File already exists: ${outputFile}`));
    process.exit(1);
  }
  
  writeFileSync(outputFile, template);
  console.log(chalk.green(`  ✓ Created: ${outputFile}`));
}

// ============================================================================
// Template Generation
// ============================================================================

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateTemplate(model: any, id: string): string {
  const typeName = model.name;
  const lines: string[] = [];
  
  lines.push(`/**`);
  lines.push(` * ${typeName}: ${id}`);
  lines.push(` * `);
  lines.push(` * Generated by speckeeper new`);
  lines.push(` */`);
  lines.push(`import type { ${typeName} } from './_models/${model.id}';`);
  lines.push('');
  lines.push(`export const ${camelCase(id)}: ${typeName} = {`);
  lines.push(`  id: '${id}',`);
  lines.push(`  // TODO: Fill in the required fields`);
  lines.push(`};`);
  lines.push('');
  
  return lines.join('\n');
}

function camelCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase());
}
