import type { CheckerBinding, ModelTemplateParams } from './types.js';

/**
 * Guidance for the checker-triggering edges the flowchart declared.
 *
 * The flowchart says which external SSOT this model is checked against; the
 * paths and scanners live in speckeeper.config.ts, so the generated file points
 * at the binding to write rather than writing a checker itself.
 */
function renderCheckerBindingGuidance(bindings: CheckerBinding[]): string {
  if (bindings.length === 0) return '';

  const lines = bindings.map(binding => {
    const target = binding.targetLabel && binding.targetLabel !== binding.targetId
      ? `${binding.targetId} (${binding.targetLabel})`
      : binding.targetId;
    return ` * - ${binding.relation} → ${target}`;
  });

  return `
// =============================================================================
// Checker binding
// =============================================================================

/**
 * The flowchart declares these checker-triggering edges for this model:
${lines.join('\n')}
 *
 * Declare a matching entry under \`sources\` in speckeeper.config.ts — its
 * \`type\`, \`paths\` and \`relation\` — so \`speckeeper check\` scans that external
 * SSOT for this model's spec IDs.
 */
`;
}

export function generateBaseModel(params: ModelTemplateParams): string {
  const schemaName = `${params.modelName}Schema`;
  const className = `${params.modelName}Model`;

  const dslImportLine = `import { requireField } from 'speckeeper/dsl';`;
  const checkerBindingGuidance = renderCheckerBindingGuidance(params.checkerBindings ?? []);

  return `/**
 * ${params.modelName} Model Definition
 *
 * Generated by speckeeper scaffold — customise as needed.
 */
import { z } from 'zod';
import { Model, RelationSchema } from 'speckeeper';
import type { LintRule, Exporter, ModelLevel } from 'speckeeper';
${dslImportLine}

// =============================================================================
// Schema Definition
// =============================================================================

export const ${schemaName} = z.object({
  id: z.string(),
  name: z.string().min(1),
  description: z.string(),
  relations: z.array(RelationSchema).optional(),
});

// =============================================================================
// Type Export
// =============================================================================

export type ${params.modelName} = z.input<typeof ${schemaName}>;
${checkerBindingGuidance}
// =============================================================================
// Model Class
// =============================================================================

class ${className} extends Model<typeof ${schemaName}> {
  readonly id = '${params.modelId}';
  readonly name = '${params.modelName}';
  readonly idPrefix = '${params.idPrefix}';
  readonly schema = ${schemaName};
  readonly description = '${params.description}';
  // TODO: adjust modelLevel
  protected modelLevel: ModelLevel = '${params.level}';

  protected lintRules: LintRule<${params.modelName}>[] = [
    requireField<${params.modelName}>('description'),
  ];

  protected exporters: Exporter<${params.modelName}>[] = [];
}

export { ${className} };
`;
}
