import type { ModelTemplateParams } from './types.js';

export function generateBaseModel(params: ModelTemplateParams): string {
  const schemaName = `${params.modelName}Schema`;
  const className = `${params.modelName}Model`;

  return `/**
 * ${params.modelName} Model Definition
 *
 * Generated by speckeeper scaffold — customise as needed.
 */
import { z } from 'zod';
import { Model, RelationSchema } from 'speckeeper';
import type { LintRule, Exporter, ModelLevel } from 'speckeeper';

// =============================================================================
// Schema Definition
// =============================================================================

export const ${schemaName} = z.object({
  id: z.string(),
  name: z.string().min(1),
  description: z.string(),
  relations: z.array(RelationSchema).optional(),
});

// =============================================================================
// Type Export
// =============================================================================

export type ${params.modelName} = z.input<typeof ${schemaName}>;

// =============================================================================
// Model Class
// =============================================================================

class ${className} extends Model<typeof ${schemaName}> {
  readonly id = '${params.modelId}';
  readonly name = '${params.modelName}';
  readonly idPrefix = '${params.idPrefix}';
  readonly schema = ${schemaName};
  readonly description = '${params.description}';
  // TODO: adjust modelLevel
  protected modelLevel: ModelLevel = '${params.level}';

  protected lintRules: LintRule<${params.modelName}>[] = [
    {
      id: '${params.modelId}-has-description',
      severity: 'warning',
      message: '${params.modelName} should have a description',
      check: (spec) => !spec.description || spec.description.trim() === '',
    },
  ];

  protected exporters: Exporter<${params.modelName}>[] = [];
}

export { ${className} };
`;
}
